### ISSUE TITLE
Picture issue: x-aix 

### ISSUE THREAD

**Issue by JasmineZhihanQiu** [JasmineZhihanQiu/ds4d#5]
There are some problem in the x-aix. Please check it again @gaozf0313

**Comment by gaozf0313** [comment]
Oh yes, I know what's wrong with the data. You are right, the x-aix didn't show properly. All the kinds of appliances should be on the x-aix and the value on the y-aix. So I've done it again. I think it's ok now. You can double check it. The graph has been updated on git.
