### ISSUE TITLE
graph of when people cook

### ISSUE THREAD

**Issue by gaozf0313** [JasmineZhihanQiu/ds4d#6]
I think the latest version of the graph with the circles can not show the important points or say the obvious difference between the data. Maybe we still come back to the former version?

**Comment by gaozf0313** [comment]
@JasmineZhihanQiu Don't forget this issue.

**Comment by JasmineZhihanQiu** [comment]
sorry for check this issue late. Yeah, the former version is better. We used it in the final presentation.
